version: "3.2"

services:
  fail2ban:
    build: ./fail2ban
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban_db:/fail2ban_db
      - log_collector:/xlogs
    env_file:
      - "./fail2ban.env"
    restart: unless-stopped

volumes:
  fail2ban_db:
  log_collector:
