version: "3"

services:
  fail2ban:
    build: .
    container_name: fail2ban
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban_db:/fail2ban_db
      - log_collector:/xlogs
    env_file:
      - "./fail2ban.env"

volumes:
  fail2ban_db:
  log_collector:
